### ISSUE TITLE
pyprind causing problems in various contexts

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2#20]
**[Original report](https://bitbucket.org/cmutel/brightway2/issue/20) by Pascal Lesage (Bitbucket: [_MPa_](https://bitbucket.org/_MPa_), ).**

----------------------------------------

The use of pyprind can generate errors in certain contexts, limiting the use of Brightway2 as a backend engine.
Example:
- use on a calculation cluster, pyprind results in a "No valid output stream.", and blocks all calculations.
- for use in a GUI with no terminal (e.g. running with pythonw), similar issue.

**Comment by cmutel** [comment]
Closing, we are using `tqdm` in new work anyway.
