### ISSUE TITLE
Help with uncertainty (Monte Carlo Analysis)

### ISSUE THREAD

**Issue by TJTapajyoti** [brightway-lca/brightway2#23]
Hello, I have been using brightway2 for some time now and am trying to perform MC analysis. What I intend to do is use the uncertainty values already provided in Ecoinvent3.6 and perform LCA and LCIA calculations. I have tried to look at some tutorials but haven't found anything helpful. Many tutorials have broken links where I am not able to find the files needed for using the tutorial. Can someone kindly point me to a tutorial for performing MC analysis using the uncertainty data in ecoinvent. I want to keep my final demand, my LCIA method fixed and just analyze the uncertainty in the background data. 

Apologies for posting this as an issue.

**Comment by BenPortner** [comment]
Hello @TJTapajyoti,

You can find a code example [here](https://github.com/PoutineAndRosti/Brightway-Seminar-2017/blob/master/Day%201%20PM/Brightway%20and%20uncertainty.ipynb). If you prefer using a graphical user interface to perform MC, check the [activity-browser](https://github.com/LCA-ActivityBrowser/activity-browser).

Hope this helps.
Ben
