### ISSUE TITLE
Brightway2 Traci method obsolete

### ISSUE THREAD

**Issue by TJTapajyoti** [brightway-lca/brightway2#25]
I am using the TRACI method in the LCIA methods of Brightway2. The indicators as well as the units are not matching TRACI 2.1 from USEPA. Is there an update that corrects this error? 

For example, TRACI in Brightway has photo chemical oxidation, TRACI 2.1 has smog formation with different units. The units of carcinogenics is different as well as ecotoxicity. 
is the TRACI method in Brightway2 an earlier version? ( It says obsolete)

https://www.epa.gov/chemical-research/tool-reduction-and-assessment-chemicals-and-other-environmental-impacts-traci

**Comment by cmutel** [comment]
Brightway provides some default metadata drawn from the ecoinvent database. We also provide the implementation of LCIA methods that ecoinvent releases. So, our version of TRACI comes from ecoinvent, and we don't do any checking or supplementing afterwards - and I don't have the resources to add additional methods on my own.

The US EPA has done a lot of work on linking subsequent versions of TRACI, but one would have to provide an implementation of these methods. This is not terribly difficult, but someone has to volunteer :)

Here are some examples of LCIA methods implemented outside of the ecoinvent defaults:

* [Crustal Scarcity Indicator](https://github.com/brightway-lca/brightway2/blob/master/notebooks/Importing%20Crustal%20Scarcity%20Index%20from%20Excel.ipynb)
* [AWARE](https://github.com/cmutel/bw2_aware)
* [LC-IMPACT](https://github.com/cmutel/bw2-lcimpact)
* [ReCiPe 2016](https://github.com/brightway-lca/bw_recipe_2016)
