### ISSUE TITLE
Brightway2 LCIA method (ILCD 2018) is missing 

### ISSUE THREAD

**Issue by redo-ad** [brightway-lca/brightway2#32]
I recently installed bw2 and the activity-browser and imported 975 LCIA methods, but the ILCD 2018 method is missing. My colleague has installed bw2 a few months ago and he can use the ILCD 2018 methods, even though installed in the same way. I reinstalled bw2 using the brightway2 recipe from @BenPortner in jupyter lab, but the ILCD 2018 is still missing. 
Is there a way to integrate the ILCD 2018 methods to bw2 and the activity browser or is there a reason why they are not included anymore?

Thanks in advance!

Adrian

**Comment by BenPortner** [comment]
Hi @redo-ad,

The ILCD 2018 method has been renamed to EF 2.0 during the last ecoinvent update. Personally, I would recommend using EF 3.0 (which was also introduced with the update), which is even more up to date.

Cheers.
Ben

**Comment by redo-ad** [comment]
Hi @BenPortner,

thank you for your quick response. 

Adrian
