### ISSUE TITLE
Incompatibility brightway / spyder

### ISSUE THREAD

**Issue by colombepey** [brightway-lca/brightway2#34]
I wanted to use brightway with spyder in my conda environment.
I encountered an error each time I tried to import the brightway package.

It turned out that it was an incompatibility between spyder and the dependency "eight"
This package seemed to be called when using Python 2, as I always use python 3, I simply deleted every reference to "eight"
After that everything works fine.

**Comment by cmutel** [comment]
Brightway 2.5 is dropping Py2 compatibility, and therefore also deleting `eight`. Thanks for the info.
