### ISSUE TITLE
Kernel dies at Package Import on Mac M1

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway2#44]
Following the [installation instructions](https://2.docs.brightway.dev/installation.html#quickstart) (tried both "Quickstart" and "Installation on Mac M1"), my kernel dies when importing any package:

```
from matplotlib import pyplot as plt
```

returns

_The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter log for further details._

The logs read

```
info 13:1:58.641: Execute Cell 2 /Users/michaelweinold/github/brightway2/notebooks/Systematic bias in Monte Carlo medians.ipynb
error 13:2:12.291: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at a.KernelShellFutureHandler.dispose (/Users/michaelweinold/.vscode/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/node_modules/@jupyterlab/services.js:2:32353)
	at /Users/michaelweinold/.vscode/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/node_modules/@jupyterlab/services.js:2:26572
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/Users/michaelweinold/.vscode/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/node_modules/@jupyterlab/services.js:2:26557)
	at /Users/michaelweinold/.vscode/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/node_modules/@jupyterlab/services.js:2:29000
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 13:2:12.291: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 13:2:12.291: Cancel all remaining cells true || Error || undefined
info 13:2:12.291: Cancel pending cells
info 13:2:12.291: Cell 2 executed with state Error
```

System: macOS Monterey, 12.4 (21F79)
conda 4.13.0

**Comment by michaelweinold** [comment]
Related: efforts to release platform specific conda packages (pypardiso solver for Win platform, umfpack solver for macOS ARM64 platform):

https://github.com/brightway-lca/brightway2/issues/47
https://github.com/cmutel/conda-recipes/issues/6

**Comment by cmutel** [comment]
Should be fixed with _nosolver conda packages.
