### ISSUE TITLE
Conceptual inconsistencies with activities/products and exchanges in ecoinvent

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2#7]
**[Original report](https://bitbucket.org/cmutel/brightway2/issue/7) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Current importing does not really make sense - all links are from activities to activities, and flows or reference products are only considered as metadata of an activity. However, a reference product has a different name than an activity, and therefore we can easily get confused writing e.g. exporters.

The current system works, and the calculations are OK, but maybe we want to consider being more explicit or better documenting the current assumptions that more or less disregard product names in exchanges.

**Comment by cmutel** [comment]
Adding products will come in bw3, this works fine for now.
