### ISSUE TITLE
I cannot install brightway 2 with anaconda

### ISSUE THREAD

**Issue by PGjedde** [brightway-lca/brightway2#75]
Trying to install brightway2 in 2 different ways, and none work:

**As I should according to [anaconda](https://anaconda.org/cmutel/brightway2)**:
```
C:\Users\username>conda install cmutel::brightway2
```
> Channels:
>  - defaults
>  - cmutel
> Platform: win-64
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - cmutel::brightway2
> 
> Current channels:
> 
>   - defaults
>   - https://conda.anaconda.org/cmutel
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
> https://anaconda.org
> 
> and use the search bar at the top of the page.

**According to the [official documentation](https://docs.brightway.dev/en/legacy/content/installation/installation.html)**:
```
C:\Users\username>conda create -n bw brightway2 jupyterlab
```
> Channels:
>  - defaults
> Platform: win-64
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - brightway2
> 
> Current channels:
> 
>   - defaults
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>  https://anaconda.org
> 
> and use the search bar at the top of the page.

**Comment by moritzos** [comment]
Hello @PGjedde,

could you fix the issue described in your comment? I have the same problem and would be interested in a solution.

**Comment by PGjedde** [comment]
Hi @moritzos,
Yes I suggest using pip for installation as this is "constant" and allows you to install the last legacy version of Brightway 2 (note: _not_ 2.5).

To install in a new conda environment:
``` python
conda create -n bw20 -c conda-forge pip
conda activate bw20
pip install brightway2==2.4.5
```

And if you use JupyterLab you can create the first conda environment with following:
```python
conda create -n bw20 -c conda-forge pip ipykernel jupyterlab
```

Let me know if it also works for you.
